/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import DBConn.DBConnection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Divya
 */
public class addQues extends javax.swing.JInternalFrame {

    /**
     * Creates new form addQues
     */
    String admin;
    
    public addQues(String user) {
        initComponents();
        getAllSubject();
        findallSubject();
        admin = user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_ques = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        txt_opt1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_opt2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_opt3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_opt4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_correctans = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btn_addques = new javax.swing.JButton();
        cmb_sub = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Add Question");

        jLabel1.setText("Question");

        txt_ques.setColumns(20);
        txt_ques.setRows(5);
        jScrollPane1.setViewportView(txt_ques);

        jLabel2.setText("Option 1:");

        jLabel3.setText("Option 2:");

        jLabel4.setText("Option 3:");

        jLabel5.setText("Option 4:");

        txt_opt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_opt4ActionPerformed(evt);
            }
        });

        jLabel6.setText("Correct:");

        jLabel7.setText("Subject:");

        btn_addques.setText("Add Question");
        btn_addques.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addquesActionPerformed(evt);
            }
        });

        cmb_sub.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmb_sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_subActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_addques)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txt_opt1))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txt_opt2))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txt_opt3))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_correctans)
                                .addComponent(txt_opt4)
                                .addComponent(cmb_sub, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_opt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_opt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_opt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_opt4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_correctans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmb_sub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(btn_addques)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addquesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addquesActionPerformed
        // TODO add your handling code here:
        String ques=txt_ques.getText();
        String opt1=txt_opt1.getText();
        String opt2=txt_opt2.getText();
        String opt3=txt_opt3.getText();
        String opt4=txt_opt4.getText();
        String cor=txt_correctans.getText();
        String sub=(String) cmb_sub.getSelectedItem();
        String adminname= admin;
        String empty = "";
        
        if(ques.equals(empty)){
            JOptionPane.showMessageDialog(this, "Question is empty! Please re-enter...");
        }
        else if(opt1.equals(empty)){
            JOptionPane.showMessageDialog(this, "Option 1 is empty! Please re-enter...");
        }
        else if(opt2.equals(empty)){
            JOptionPane.showMessageDialog(this, "Option 2 is empty! Please re-enter...");
        }
        else if(opt3.equals(empty)){
            JOptionPane.showMessageDialog(this, "Option 3 is empty! Please re-enter...");
        }
        else if(opt4.equals(empty)){
            JOptionPane.showMessageDialog(this, "Option 4 is empty! Please re-enter...");
        }
        else if(cor.equals(empty)){
            JOptionPane.showMessageDialog(this, "Correct Answer is empty! Please re-enter...");
        }
        else if(sub.equals(empty)){
            JOptionPane.showMessageDialog(this, "Subject is empty! Please re-enter...");
        }
        else{
            try {
                DBConnection tdc= new DBConnection();
                int result=tdc.addQues(ques,opt1,opt2,opt3,opt4,cor,sub);
                if(result>0)
                {
                    JOptionPane.showMessageDialog(null,"Question added Successfully"); 
                    txt_ques.setText("");
                    txt_correctans.setText("");
                    txt_opt1.setText("");
                    txt_opt2.setText("");
                    txt_opt3.setText("");
                    txt_opt4.setText("");
                    
                  
                    
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"Unable to add Question");
                    txt_ques.setText("");
                    txt_correctans.setText("");
                    txt_opt1.setText("");
                    txt_opt2.setText("");
                    txt_opt3.setText("");
                    txt_opt4.setText("");
                }    
         }
        
         catch (Exception ex) {
         
         }
        
        }  
        
        //System.out.println("Question:"+ques+" "+"1:"+opt1+" "+"2:"+opt2+" "+"3:"+opt3+" "+"4:"+opt4+" "+"correct:"+cor+" "+"Sub:"+sub+" "+"user:"+adminname);
        
        
        
    }//GEN-LAST:event_btn_addquesActionPerformed

    private void cmb_subActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_subActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_subActionPerformed

    private void txt_opt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_opt4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_opt4ActionPerformed

        public List<String> getAllSubject(){
        List<String> subject = new ArrayList<>();
        try {
            String query = "Select * from subjects"; /*where project_owner=?*/
            //stmt.setInt(1, user.getUserId());
            DBConnection dc=new DBConnection();
            PreparedStatement stmt = dc.conn.prepareStatement(query);
            ResultSet rs = stmt.executeQuery();
            while(rs.next()){
                subject.add(rs.getString("SubjectName"));
            }
        } catch (SQLException ex) {
            
        }
        return subject;
    }

        private void findallSubject() {
        cmb_sub.removeAllItems();
        List<String> sub = null;
        List<String> subList = null;
        DefaultComboBoxModel dcm = null;
        subList = getAllSubject();
        dcm = new DefaultComboBoxModel(subList.toArray());
        cmb_sub.setModel(dcm);
    }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addques;
    private javax.swing.JComboBox<String> cmb_sub;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_correctans;
    private javax.swing.JTextField txt_opt1;
    private javax.swing.JTextField txt_opt2;
    private javax.swing.JTextField txt_opt3;
    private javax.swing.JTextField txt_opt4;
    private javax.swing.JTextArea txt_ques;
    // End of variables declaration//GEN-END:variables
}
